"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert("Icons", [
      { icon_url: "http://localhost:3333/academic-cap-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/ad-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/adjustments-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/aerial-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/airplane-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/airplay-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/airpod-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/airpods-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/align-horizontally-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/aquarius-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/archive-book-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/archive-minus-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/archive-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/at-symbol-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/award-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/bitcoin-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/book-open-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/bookmark-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/box-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/briefcase-alt-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/building-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/bulb-on-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/cake-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/cash-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/chart-bar-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/chart-bubble-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/chart-pie-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/code-alt-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/color-swatch-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/credit-card-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/database-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/desktop-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/diamond-svgrepo-com.svg " },
      { icon_url: "http://localhost:3333/document-report-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/dollar-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/duplicate-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/edit-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/euro-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/filter-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/fingerprint-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/folder-open-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/folder-remove-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/gauge-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/ghost-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/gift-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/github-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/globe-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/goblet-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/heart-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/help-alt-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/home-alt-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/id-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/inbox-full-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/justify-fill-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/key-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/keyboard-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/lamp-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/laptop-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/license-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/link-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/lock-open-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/luggage-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/mail-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/map-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/mastercard-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/mobile-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/monitor-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/more-horizontal-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/mug-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/paperclip-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/pause-alt-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/paypal-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/pencil-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/phone-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/photo-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/pin-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/pound-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/printer-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/scissors-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/shopping-bag-svgrepo-com.svg " },
      { icon_url: "http://localhost:3333/shopping-cart-svgrepo-com.svg " },
      { icon_url: "http://localhost:3333/speaker-svgrepo-com.svg " },
      { icon_url: "http://localhost:3333/star-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/sun-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/support-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/tablet-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/ticket-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/user-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/users-svgrepo-com.svg" },
      { icon_url: "http://localhost:3333/watches-svgrepo-com.svg" },
    ]);
  },
  async down(queryIhttp, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
