"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert("Icons", [
      { icon_url: "academic-cap-svgrepo-com.svg" },
      { icon_url: "ad-svgrepo-com.svg" },
      { icon_url: "adjustments-svgrepo-com.svg" },
      { icon_url: "aerial-svgrepo-com.svg" },
      { icon_url: "airplane-svgrepo-com.svg" },
      { icon_url: "airplay-svgrepo-com.svg" },
      { icon_url: "airpod-svgrepo-com.svg" },
      { icon_url: "airpods-svgrepo-com.svg" },
      { icon_url: "align-horizontally-svgrepo-com.svg" },
      { icon_url: "aquarius-svgrepo-com.svg" },
      { icon_url: "archive-book-svgrepo-com.svg" },
      { icon_url: "archive-minus-svgrepo-com.svg" },
      { icon_url: "archive-svgrepo-com.svg" },
      { icon_url: "at-symbol-svgrepo-com.svg" },
      { icon_url: "award-svgrepo-com.svg" },
      { icon_url: "bitcoin-svgrepo-com.svg" },
      { icon_url: "book-open-svgrepo-com.svg" },
      { icon_url: "bookmark-svgrepo-com.svg" },
      { icon_url: "box-svgrepo-com.svg" },
      { icon_url: "briefcase-alt-svgrepo-com.svg" },
      { icon_url: "building-svgrepo-com.svg" },
      { icon_url: "bulb-on-svgrepo-com.svg" },
      { icon_url: "cake-svgrepo-com.svg" },
      { icon_url: "cash-svgrepo-com.svg" },
      { icon_url: "chart-bar-svgrepo-com.svg" },
      { icon_url: "chart-bubble-svgrepo-com.svg" },
      { icon_url: "chart-pie-svgrepo-com.svg" },
      { icon_url: "code-alt-svgrepo-com.svg" },
      { icon_url: "color-swatch-svgrepo-com.svg" },
      { icon_url: "credit-card-svgrepo-com.svg" },
      { icon_url: "database-svgrepo-com.svg" },
      { icon_url: "desktop-svgrepo-com.svg" },
      { icon_url: "diamond-svgrepo-com.svg " },
      { icon_url: "document-report-svgrepo-com.svg" },
      { icon_url: "dollar-svgrepo-com.svg" },
      { icon_url: "duplicate-svgrepo-com.svg" },
      { icon_url: "edit-svgrepo-com.svg" },
      { icon_url: "euro-svgrepo-com.svg" },
      { icon_url: "filter-svgrepo-com.svg" },
      { icon_url: "fingerprint-svgrepo-com.svg" },
      { icon_url: "folder-open-svgrepo-com.svg" },
      { icon_url: "folder-remove-svgrepo-com.svg" },
      { icon_url: "gauge-svgrepo-com.svg" },
      { icon_url: "ghost-svgrepo-com.svg" },
      { icon_url: "gift-svgrepo-com.svg" },
      { icon_url: "github-svgrepo-com.svg" },
      { icon_url: "globe-svgrepo-com.svg" },
      { icon_url: "goblet-svgrepo-com.svg" },
      { icon_url: "heart-svgrepo-com.svg" },
      { icon_url: "help-alt-svgrepo-com.svg" },
      { icon_url: "home-alt-svgrepo-com.svg" },
      { icon_url: "id-svgrepo-com.svg" },
      { icon_url: "inbox-full-svgrepo-com.svg" },
      { icon_url: "justify-fill-svgrepo-com.svg" },
      { icon_url: "key-svgrepo-com.svg" },
      { icon_url: "keyboard-svgrepo-com.svg" },
      { icon_url: "lamp-svgrepo-com.svg" },
      { icon_url: "laptop-svgrepo-com.svg" },
      { icon_url: "license-svgrepo-com.svg" },
      { icon_url: "link-svgrepo-com.svg" },
      { icon_url: "lock-open-svgrepo-com.svg" },
      { icon_url: "luggage-svgrepo-com.svg" },
      { icon_url: "mail-svgrepo-com.svg" },
      { icon_url: "map-svgrepo-com.svg" },
      { icon_url: "mastercard-svgrepo-com.svg" },
      { icon_url: "mobile-svgrepo-com.svg" },
      { icon_url: "monitor-svgrepo-com.svg" },
      { icon_url: "more-horizontal-svgrepo-com.svg" },
      { icon_url: "mug-svgrepo-com.svg" },
      { icon_url: "paperclip-svgrepo-com.svg" },
      { icon_url: "pause-alt-svgrepo-com.svg" },
      { icon_url: "paypal-svgrepo-com.svg" },
      { icon_url: "pencil-svgrepo-com.svg" },
      { icon_url: "phone-svgrepo-com.svg" },
      { icon_url: "photo-svgrepo-com.svg" },
      { icon_url: "pin-svgrepo-com.svg" },
      { icon_url: "pound-svgrepo-com.svg" },
      { icon_url: "printer-svgrepo-com.svg" },
      { icon_url: "scissors-svgrepo-com.svg" },
      { icon_url: "shopping-bag-svgrepo-com.svg " },
      { icon_url: "shopping-cart-svgrepo-com.svg " },
      { icon_url: "speaker-svgrepo-com.svg " },
      { icon_url: "star-svgrepo-com.svg" },
      { icon_url: "sun-svgrepo-com.svg" },
      { icon_url: "support-svgrepo-com.svg" },
      { icon_url: "tablet-svgrepo-com.svg" },
      { icon_url: "ticket-svgrepo-com.svg" },
      { icon_url: "user-svgrepo-com.svg" },
      { icon_url: "users-svgrepo-com.svg" },
      { icon_url: "watches-svgrepo-com.svgpublic/yen-svgrepo-com.svg" },
    ]);
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
